apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 2
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: front
          image: aleczheng/license-front
          resources:
            requests:
              cpu: "5m"
              memory: "200Mi"
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_HOST
              value: back-cluster-ip
