version: "3"
services:
  db:
    image: "mysql:5"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - license-network
  back:
    image: aleczheng/license-back:2d0d0eee4bcdc65a3b8f342591762c28e3240390
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=root
      - ES_URL=http://es01:9200  
  es01:
    image: elasticsearch:7.10.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - license-network
  kibana01:
    image: kibana:7.10.1
    container_name: kibana01
    environment:
      - OPENSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      - license-network
  lvmeng:
    image: plosa/lvmeng:4.0
    container_name: lvmeng
    ports:
      - 8082:8080
    networks:
      - license-network
  compatiableTable:
    image: haohaoxuexi2/compatibility:v1
    container_name: compatibility
    ports:
      - 8083:5000
    networks:
      - license-network
networks:
  license-network:
    driver: bridge
